openapi: 3.1.0
info:
  title: Protalko API
  description: ''
  license:
    name: ''
  version: 0.1.0
paths:
  /health:
    get:
      tags:
      - health
      operationId: health
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
      - {}
  /users/{user_id}:
    get:
      tags:
      - users
      operationId: getUserById
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserPresentation'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
      - {}
components:
  schemas:
    ErrorResponse:
      type: object
      required:
      - message
      properties:
        message:
          type: string
    UserPresentation:
      type: object
      required:
      - id
      - visible_id
      - name
      properties:
        id:
          type: string
        name:
          type: string
        visible_id:
          type: string
tags:
- name: health
  description: APIの正常性チェック
- name: user
  description: ユーザー関連の操作
